### ISSUE TITLE
Typo "plane text"

### ISSUE THREAD

**Issue by sunnz** [TakuKobayashi/UnityCipher#5]
https://github.com/TakuKobayashi/UnityCipher/blob/f37d10ca2ae8b7ce055e9ae1ea11f9f88c7cfa76/Assets/UnityCipher/Scripts/RijndaelEncryption.cs#L28

I think you meant "plain text" and "plain binary" instead of "plane text" and "plane binary".

**Comment by TakuKobayashi** [comment]
@sunnz thank you for comment. I have fixed it.
https://github.com/TakuKobayashi/UnityCipher/pull/6
